# Config Version - 2.2.1
telegram:
  enabled: true
  botToken: "YOUR_TELEGRAM_BOT_TOKEN"

matrix:
  enabled: true
  homeserver: "matrix.example.org"
  username: "your_bot_username"
  password: "your_bot_password"
  roomId: "!your_room_id:matrix.example.org"
# languages: en, ru
language: "en"
formats:
  telegram-to-minecraft: "[TG] {sender}: {message}"
  minecraft-to-telegram: "[MC] {sender}: {message}"
  matrix-to-minecraft: "[MX] {sender}: {message}"
  minecraft-to-matrix: "[MC] {sender}: {message}"

settings:
  check-for-updates: true
  first-run-setup: true
