name: TeleNukkit
version: 1.0.0
main: com.debianrose.TeleNukkit.Main
api: ["1.0.0"]
author: debianrose
description: Bridge Between Telegram/Matrix And Nukkit
commands:
  setlanguage:
    description: Change the plugin language.
    usage: /setlanguage <ru|en|es|ua|kz|ar>
    permission: op
permissions:
  telegrambridge.setlanguage:
    description: Allows changing the plugin language.
    default: op
